spring.application.name=decathlon

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/decathlon
spring.datasource.username=postgres
spring.datasource.password=root

# Pane siia oma mockapi.io projekti URL-id (vt kirjeldus.txt). Tühjaks jättes kasutab rakendus naiteandmeid.
decathlon.mockapi.judges-url=
decathlon.mockapi.locations-url=