spring.application.name=teisendamine
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/teisendamine
spring.datasource.username=postgres
spring.datasource.password=root