#Render database connection - täida need, kui deploy'd Render'isse (vt 07_20.03-deploy/JUHEND.md)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

everypay.account-name=
everypay.api-username=
everypay.api-secret=
everypay.customer-url=http://err.ee
